import { useEffect } from 'react';
import type { RefObject } from 'react';
import { loadMermaid } from '../components/MarkdownRenderer';

let idCounter = 0;

/** Render mermaid/gantt code blocks inside a container element. */
export function useMermaidRender(
  containerRef: RefObject<HTMLElement | null>,
  dependency: unknown,
) {
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    const codeBlocks = el.querySelectorAll<HTMLElement>(
      'code.language-mermaid, code.language-gantt'
    );
    if (codeBlocks.length === 0) return;

    let cancelled = false;

    (async () => {
      let mermaid;
      try {
        mermaid = await loadMermaid();
      } catch {
        return;
      }
      if (cancelled) return;

      for (const codeEl of codeBlocks) {
        if (cancelled) break;
        const pre = codeEl.parentElement;
        if (!pre || pre.tagName !== 'PRE') continue;

        const definition = codeEl.textContent || '';
        if (!definition.trim()) continue;

        const id = `mermaid-${++idCounter}`;
        try {
          const { svg } = await mermaid.render(id, definition);
          if (cancelled) break;

          // SVG is generated by mermaid library (trusted output), safe to insert
          const wrapper = document.createElement('div');
          wrapper.className = 'mermaid-diagram';
          wrapper.innerHTML = svg;
          pre.replaceWith(wrapper);
        } catch {
          if (cancelled) break;
          pre.classList.add('mermaid-error');
          const errSpan = document.createElement('div');
          errSpan.className = 'mermaid-error__msg';
          errSpan.textContent = 'Mermaid syntax error';
          pre.appendChild(errSpan);
        }
      }
    })();

    return () => { cancelled = true; };
  }, [dependency]); // eslint-disable-line react-hooks/exhaustive-deps
}
